package com.example.faas.aws.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "PLACEHOLDER_NOTES_TABLE_NAME")
public class Note {

    public static final String NOTES_TABLE_NAME = System.getenv("NOTES_TABLE_NAME");

    private String id;
    private String author;
    private String text;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(final String id) {
        this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "author")
    public String getAuthor() {
        return author;
    }

    public void setAuthor(final String author) {
        this.author = author;
    }

    @DynamoDBRangeKey(attributeName = "text")
    public String getText() {
        return text;
    }

    public void setText(final String text) {
        this.text = text;
    }
}
